# Generated by Django 3.1.2 on 2020-10-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0002_auto_20201026_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='media/img/'),
        ),
    ]
