# Generated by Django 3.1.2 on 2020-10-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0004_auto_20201026_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciones',
            name='numeroC',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.BigIntegerField(),
        ),
    ]
