# Generated by Django 3.1.2 on 2020-10-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0005_auto_20201026_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fcasa',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fcelular',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='departamento',
            field=models.BigIntegerField(),
        ),
    ]
