# Generated by Django 3.1.2 on 2020-11-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0006_auto_20201026_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dv',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='compras@super.cl', max_length=50, unique=True),
        ),
    ]
