# Generated by Django 3.1.2 on 2020-11-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0007_auto_20201103_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compras',
            name='id_boleta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supermercado.boleta'),
        ),
    ]
