# Generated by Django 3.1.2 on 2020-11-26 01:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0008_auto_20201119_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellidoM',
            field=models.CharField(max_length=20, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidoP',
            field=models.CharField(max_length=20, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='compras@super.cl', max_length=50, unique=True, verbose_name='e-Mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fcasa',
            field=models.BigIntegerField(verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fcelular',
            field=models.BigIntegerField(verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='calle',
            field=models.CharField(max_length=50, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='id_direccion',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Identificador de Dirección'),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='numeroC',
            field=models.BigIntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Identificador Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreP',
            field=models.CharField(max_length=50, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.BigIntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.BigIntegerField(verbose_name='Stock'),
        ),
    ]
