# Generated by Django 3.1.2 on 2020-11-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0009_auto_20201125_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Nombre tipo de producto'),
        ),
    ]
