# Generated by Django 3.1.2 on 2020-12-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0010_auto_20201125_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='supermercado.tipoproducto'),
        ),
    ]
